#!/bin/bash
# Bash script for replacing null delimiter with newlines.
# Place this file in ~/.locla/bin and ensure that the path is listed in your PATH (in ~/.bash_profile).
# Once in your PATH, you can excute this when you cd into whatever dir has your logger files.
# You can also try calling this script from another script to process directories recursively

for f in *.TXT; do
	echo "Cleaning up $f"
	cat "$f" | sed -e "s/\x00/\n/g" | gzip -c9 > "$f.gz"
done
